### ISSUE TITLE
I would like to be a part of the Milan community. Me and my teammates started a similar initiative but due to some issues, we could pull it off. So, I am willing to join the community and build something for the people.

### ISSUE THREAD

**Issue by YuvarajSingh-0** [MilanCommunity/.github#4]
### Name

Yuvaraj Singh Nidyanand

### Checklist ✅

- [X] I have followed the [organisation](https://github.com/MilanCommunity).
- [x] I will abide by all the [global rules](https://github.com/MilanCommunity/.github/blob/main/CODE_OF_CONDUCT.md) stated here.
- [x] NOTE: Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. Do this by finding your name in the [GitHub organisation list](https://github.com/orgs/MilanCommunity/people) and change the dropdown to public.

**Comment by YuvarajSingh-0** [comment]
Wouldn't the collaboration be seamless if the Milan community has any social media? Like discord ? Or some sort? I searched for connecting with dev team.... but couldn't find anything except this github. Establishing a discord server for devs would be helpful for collaboration I think.

**Comment by YuvarajSingh-0** [comment]
@tamalCodes Is there any collaboration medium for this work?

**Comment by tamalCodes** [comment]
Hi @YuvarajSingh-0 , this is an OpenSource project so we don't really have a `dev team`, everyone is contributing to the project voluntarily.

We don't really have social media as of now, reach out to milanhub.org@gmail.com for any kind of important messages. Other than you are free to look at the issues and contribute to the project along with everyone else !
